/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikelompokimk;

import java.sql.Connection;
import databases.*;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adam
 */
public class Halaman_matkul extends javax.swing.JFrame {

    /**
     * Creates new form Halaman_matkul
     */
    
    
    public Halaman_matkul() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pilihsemester = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        showtabel = new javax.swing.JTable();
        pnlTop = new javax.swing.JPanel();
        pnlActions = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        nimtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jButton1.setText("Segarkan");

        jButton2.setText("Perbarui");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pilihsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih:", "satu", "dua" }));
        pilihsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihsemesterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel1.setText("Semester");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        showtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Mata Kuliah", "SKS", "Angka", "Huruf", "Indeks", "SKS*Indeks"
            }
        ));
        showtabel.setRowHeight(35);
        showtabel.setSelectionBackground(new java.awt.Color(204, 255, 102));
        showtabel.setShowGrid(true);
        jScrollPane3.setViewportView(showtabel);

        pnlTop.setBackground(new java.awt.Color(50, 27, 140));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlActions.setBackground(new java.awt.Color(50, 27, 140));
        pnlActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home20/images/icons8_minus_18px_1.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMinimize);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home20/images/icons8_multiply_18px_1.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pnlActions.add(lblClose);

        pnlTop.add(pnlActions, java.awt.BorderLayout.LINE_END);

        pnlTitle.setBackground(new java.awt.Color(50, 27, 140));
        pnlTitle.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));

        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Admin ");
        pnlTitle.add(lblTitle);

        pnlTop.add(pnlTitle, java.awt.BorderLayout.LINE_START);

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("NIM");

        jButton4.setText("Hitung");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nimtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(pilihsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(271, 271, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(nimtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int xy, xx;
    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        Halaman_matkul.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (Halaman_matkul.this.getExtendedState() == MAXIMIZED_BOTH) {
                Halaman_matkul.this.setExtendedState(JFrame.NORMAL);
            } else {
                Halaman_matkul.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTopMouseClicked
    
    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Pilihan_admin utama = new Pilihan_admin();
        utama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String semester = pilihsemester.getSelectedItem().toString();

            String nim, angka1, angka2, angka3, angka4, angka5, angka6, angka7, angka8, huruf1, huruf2, huruf3, huruf4, satu, huruf5, huruf6, huruf7, huruf8, indeks1, indeks2, indeks3, indeks4, indeks5, indeks6, indeks7, indeks8, total1, total2, total3, total4, total5, total6, total7, total8;
            Connection conn = (Connection) databaselaporan.connectDatabaseLaporan();
            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel) showtabel.getModel();
            nim = nimtxt.getText();
            angka1 = tableModel.getValueAt(0, 3).toString();
            angka2 = tableModel.getValueAt(1, 3).toString();
            angka3 = tableModel.getValueAt(2, 3).toString();
            angka4 = tableModel.getValueAt(3, 3).toString();
            angka5 = tableModel.getValueAt(4, 3).toString();
            angka6 = tableModel.getValueAt(5, 3).toString();
            angka7 = tableModel.getValueAt(6, 3).toString();
            angka8 = tableModel.getValueAt(7, 3).toString();
            huruf1 = tableModel.getValueAt(0, 4).toString();
            huruf2 = tableModel.getValueAt(1, 4).toString();
            huruf3 = tableModel.getValueAt(2, 4).toString();
            huruf4 = tableModel.getValueAt(3, 4).toString();
            huruf5 = tableModel.getValueAt(4, 4).toString();
            huruf6 = tableModel.getValueAt(5, 4).toString();
            huruf7 = tableModel.getValueAt(6, 4).toString();
            huruf8 = tableModel.getValueAt(7, 4).toString();
            indeks1 = tableModel.getValueAt(0, 5).toString();
            indeks2 = tableModel.getValueAt(1, 5).toString();
            indeks3 = tableModel.getValueAt(2, 5).toString();
            indeks4 = tableModel.getValueAt(3, 5).toString();
            indeks5 = tableModel.getValueAt(4, 5).toString();
            indeks6 = tableModel.getValueAt(5, 5).toString();
            indeks7 = tableModel.getValueAt(6, 5).toString();
            indeks8 = tableModel.getValueAt(7, 5).toString();
            total1 = tableModel.getValueAt(0, 6).toString();
            total2 = tableModel.getValueAt(1, 6).toString();
            total3 = tableModel.getValueAt(2, 6).toString();
            total4 = tableModel.getValueAt(3, 6).toString();
            total5 = tableModel.getValueAt(4, 6).toString();
            total6 = tableModel.getValueAt(5, 6).toString();
            total7 = tableModel.getValueAt(6, 6).toString();
            total8 = tableModel.getValueAt(7, 6).toString();

            String sql = "UPDATE " + semester + " set angka1=?,"
                    + "angka2=?,"
                    + "angka3=?,"
                    + "angka4=?,"
                    + "angka5=?,"
                    + "angka6=?,"
                    + "angka7=?,"
                    + "angka8=?,"
                    + "huruf1=?,"
                    + "huruf2=?,"
                    + "huruf3=?,"
                    + "huruf4=?,"
                    + "huruf5=?,"
                    + "huruf6=?,"
                    + "huruf7=?,"
                    + "huruf8=?,"
                    + "indeks1=?,"
                    + "indeks2=?,"
                    + "indeks3=?,"
                    + "indeks4=?,"
                    + "indeks5=?,"
                    + "indeks6=?,"
                    + "indeks7=?,"
                    + "indeks8=?,"
                    + "total1=?,"
                    + "total2=?,"
                    + "total3=?,"
                    + "total4=?,"
                    + "total5=?,"
                    + "total6=?,"
                    + "total7=?,"
                    + "total8=? where nim = ?  ";

            PreparedStatement prepare = conn.prepareStatement(sql);

            prepare.setString(1, angka1);
            prepare.setString(2, angka2);
            prepare.setString(3, angka3);
            prepare.setString(4, angka4);
            prepare.setString(5, angka5);
            prepare.setString(6, angka6);
            prepare.setString(7, angka7);
            prepare.setString(8, angka8);
            prepare.setString(9, huruf1);
            prepare.setString(10, huruf2);
            prepare.setString(11, huruf3);
            prepare.setString(12, huruf4);
            prepare.setString(13, huruf5);
            prepare.setString(14, huruf6);
            prepare.setString(15, huruf7);
            prepare.setString(16, huruf8);
            prepare.setString(17, indeks1);
            prepare.setString(18, indeks2);
            prepare.setString(19, indeks3);
            prepare.setString(20, indeks4);
            prepare.setString(21, indeks5);
            prepare.setString(22, indeks6);
            prepare.setString(23, indeks7);
            prepare.setString(24, indeks8);
            prepare.setString(25, total1);
            prepare.setString(26, total2);
            prepare.setString(27, total3);
            prepare.setString(28, total4);
            prepare.setString(29, total5);
            prepare.setString(30, total6);
            prepare.setString(31, total7);
            prepare.setString(32, total8);
            prepare.setString(33, nim);

            // exequte query
            prepare.executeUpdate();
            
              // simpan dilapoaran NIM
          
             if(nimtxt.getText().equals("")){
             JOptionPane.showMessageDialog(null, "NIM tidak ditemukan", "Username gagal", JOptionPane.WARNING_MESSAGE);           
             }
            
            //end laporan NIM
            
            
        } catch (SQLException e) {
      JOptionPane.showMessageDialog(null, "Data ada yang belum di isi", "Eror data", 2);
 
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void pilihsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihsemesterActionPerformed
        // TODO add your handling code here:
        try{
         Statement stat = (Statement)databasematakuliah.connectDatabaseMatkul().createStatement();
         String semester = pilihsemester.getSelectedItem().toString();
         String sql = "select * from "+ semester;
         ResultSet rs = stat.executeQuery(sql);
         DefaultTableModel tableModel;
         tableModel = (DefaultTableModel) showtabel.getModel();
          tableModel.setRowCount(0);
            while (rs.next()) {
                tableModel.addRow((new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(4)
                }));
            }
            
            
            
        }catch(SQLException e){
             Logger.getLogger(Halaman_matkul.class.getName()).log(Level.SEVERE, null, e);
        }
            
    }//GEN-LAST:event_pilihsemesterActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Hitung Huruf
        int baris = showtabel.getRowCount();
        for (int i = 0; i < baris; i++) {
            double kolom = Double.parseDouble(showtabel.getValueAt(i, 3).toString());

            if (kolom >= 79) {
                showtabel.setValueAt("A", i, 4);
            } else if (kolom >= 69 && kolom < 79) {
                showtabel.setValueAt("B", i, 4);
            } else if (kolom >= 59 && kolom < 69) {
                showtabel.setValueAt("C", i, 4);

            } else if (kolom >= 49 && kolom < 59) {
                showtabel.setValueAt("D", i, 4);
            } else if (kolom < 49) {
                showtabel.setValueAt("T", i, 4);
            }
        }
        
        // Hitung Indeks
        for(int i=0; i< baris;i++){
           String huruf= showtabel.getValueAt(i, 4).toString();
           if(huruf.equals("A")){
              showtabel.setValueAt(4.00, i, 5); 
           }else if(huruf.equals("B")){
               showtabel.setValueAt(3.00, i, 5);
           }else if(huruf.equals("C")){
               showtabel.setValueAt(2.00, i, 5);
           }else if(huruf.equals("D")){
             showtabel.setValueAt(1.00, i, 5);

           }else if(huruf.equals("T")){
              showtabel.setValueAt(0.00, i, 5);

           }
        }
        
        // Hitung SKS x indeks
        for(int i=0;i<baris;i++){
            double sks= Double.parseDouble(showtabel.getValueAt(i, 2).toString());
            double indeks = Double.parseDouble(showtabel.getValueAt(i, 5).toString());
            sks *= indeks;
            showtabel.setValueAt(sks, i, 6);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_matkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField nimtxt;
    private javax.swing.JComboBox<String> pilihsemester;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable showtabel;
    // End of variables declaration//GEN-END:variables
}
