/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikelompokimk;

import java.awt.Desktop;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author adam
 */
public class Halaman_utama extends javax.swing.JFrame {
    // variabel
   
    int i = 0;
   
    /**
     * Creates new form Halaman_utama
     */
    // instance obejt
    public Halaman_utama() {
        initComponents();
         
       
        

    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Alurpendaftaran = new javax.swing.JPanel();
        alurjlabel = new javax.swing.JLabel();
        pendaftaran = new javax.swing.JPanel();
        daftarlabel = new javax.swing.JLabel();
        bantuan = new javax.swing.JPanel();
        bantulabel = new javax.swing.JLabel();
        pnlTop = new javax.swing.JPanel();
        pnlActions = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 51));

        jLabel2.setFont(new java.awt.Font("Manjari", 1, 24)); // NOI18N
        jLabel2.setText("UNIVERSITAS AKAGAMY");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasikelompokimk/gambar/loko kampus.png"))); // NOI18N

        Alurpendaftaran.setBackground(new java.awt.Color(0,0,0,80));
        Alurpendaftaran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Alurpendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlurpendaftaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlurpendaftaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlurpendaftaranMouseExited(evt);
            }
        });

        alurjlabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        alurjlabel.setText("Alur Pendaftaran");

        javax.swing.GroupLayout AlurpendaftaranLayout = new javax.swing.GroupLayout(Alurpendaftaran);
        Alurpendaftaran.setLayout(AlurpendaftaranLayout);
        AlurpendaftaranLayout.setHorizontalGroup(
            AlurpendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlurpendaftaranLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(alurjlabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        AlurpendaftaranLayout.setVerticalGroup(
            AlurpendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlurpendaftaranLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(alurjlabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pendaftaran.setBackground(new java.awt.Color(0,0,0,80));
        pendaftaran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendaftaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pendaftaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pendaftaranMouseExited(evt);
            }
        });

        daftarlabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        daftarlabel.setText("Pendaftaran");

        javax.swing.GroupLayout pendaftaranLayout = new javax.swing.GroupLayout(pendaftaran);
        pendaftaran.setLayout(pendaftaranLayout);
        pendaftaranLayout.setHorizontalGroup(
            pendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pendaftaranLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(daftarlabel)
                .addGap(33, 33, 33))
        );
        pendaftaranLayout.setVerticalGroup(
            pendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pendaftaranLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(daftarlabel)
                .addGap(14, 14, 14))
        );

        bantuan.setBackground(new java.awt.Color(0,0,0,80));
        bantuan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bantuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bantuanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bantuanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bantuanMouseExited(evt);
            }
        });

        bantulabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        bantulabel.setText("Bantuan");

        javax.swing.GroupLayout bantuanLayout = new javax.swing.GroupLayout(bantuan);
        bantuan.setLayout(bantuanLayout);
        bantuanLayout.setHorizontalGroup(
            bantuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bantuanLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bantulabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        bantuanLayout.setVerticalGroup(
            bantuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bantuanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bantulabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlTop.setBackground(new java.awt.Color(50, 27, 140));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlActions.setBackground(new java.awt.Color(50, 27, 140));
        pnlActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home20/images/icons8_minus_18px_1.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMinimize);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home20/images/icons8_multiply_18px_1.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pnlActions.add(lblClose);

        pnlTop.add(pnlActions, java.awt.BorderLayout.LINE_END);

        pnlTitle.setBackground(new java.awt.Color(50, 27, 140));
        pnlTitle.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));

        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Akagami University");
        pnlTitle.add(lblTitle);

        pnlTop.add(pnlTitle, java.awt.BorderLayout.LINE_START);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(Alurpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(bantuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alurpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bantuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int xy, xx;
    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        Halaman_utama.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (Halaman_utama.this.getExtendedState() == MAXIMIZED_BOTH) {
                Halaman_utama.this.setExtendedState(JFrame.NORMAL);
            } else {
                Halaman_utama.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTopMouseClicked

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void AlurpendaftaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlurpendaftaranMouseEntered
        // TODO add your handling code here:
        Alurpendaftaran.setBackground(new java.awt.Color(255, 255, 255));
        alurjlabel.setForeground(new java.awt.Color(102, 204, 0));
    }//GEN-LAST:event_AlurpendaftaranMouseEntered

    private void AlurpendaftaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlurpendaftaranMouseExited
        // TODO add your handling code here:
        Alurpendaftaran.setBackground(new java.awt.Color(0, 0, 0, 80));
        alurjlabel.setForeground(new java.awt.Color(0, 0, 0));

    }//GEN-LAST:event_AlurpendaftaranMouseExited

    private void pendaftaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendaftaranMouseEntered
        // TODO add your handling code here:
        pendaftaran.setBackground(new java.awt.Color(255, 255, 255));
        daftarlabel.setForeground(new java.awt.Color(102, 204, 0));
    }//GEN-LAST:event_pendaftaranMouseEntered

    private void pendaftaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendaftaranMouseExited
        // TODO add your handling code here:
        pendaftaran.setBackground(new java.awt.Color(0, 0, 0, 80));
        daftarlabel.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_pendaftaranMouseExited

    private void bantuanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bantuanMouseEntered
        // TODO add your handling code here:
         bantuan.setBackground(new java.awt.Color(255, 255, 255));
        bantulabel.setForeground(new java.awt.Color(102, 204, 0));
    }//GEN-LAST:event_bantuanMouseEntered

    private void bantuanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bantuanMouseExited
        // TODO add your handling code here:
         bantuan.setBackground(new java.awt.Color(0, 0, 0, 80));
        bantulabel.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_bantuanMouseExited

    private void AlurpendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlurpendaftaranMouseClicked
        // TODO add your handling code here:
        AlurPendaftaran alur= new AlurPendaftaran();
        alur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AlurpendaftaranMouseClicked

    private void pendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendaftaranMouseClicked
        // TODO add your handling code here:
        HalamanDaftar daftar=new HalamanDaftar();
        daftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pendaftaranMouseClicked

    private void bantuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bantuanMouseClicked
        // TODO add your handling code here:
        HalamanHelp help=new HalamanHelp();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bantuanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        logInMenu login=new  logInMenu();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Halaman_utama().setVisible(true);

            }
        });
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "aplikasi crash", "error crash", JOptionPane.ERROR_MESSAGE);            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alurpendaftaran;
    private javax.swing.JLabel alurjlabel;
    private javax.swing.JPanel bantuan;
    private javax.swing.JLabel bantulabel;
    private javax.swing.JLabel daftarlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pendaftaran;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
