package aplikasikelompokimk;

import databases.DBConnection;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileInputStream;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ra$h
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
   //Image path 
//    String imagePath = null;
//    
//    ///
//    String ImageName = null;
//    byte[] image = null;
    public static String userName,password;
    
    
    public registration() {
        initComponents();
           
    }

    
//    public ImageIcon ResizeImage(String imagePath, byte [] pic){
//    
//    ImageIcon myImage = null;
//    
//    if (imagePath != null){
//    
//    myImage = new ImageIcon(imagePath);
//    
//    }else {
//       myImage = new ImageIcon(pic);
//    }
//    
//    Image img = myImage.getImage();
//    Image img2 = img.getScaledInstance(jLabel8_ImageViewer.getWidth(), jLabel8_ImageViewer.getHeight(), Image.SCALE_SMOOTH);
//    
//    ImageIcon image = new ImageIcon(img2);
//    return image;
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1_ReUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2_closeButton = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Nama pengguna");

        jTextField1_ReUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1_ReUsernameKeyTyped(evt);
            }
        });

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        jButton3.setText("Lanjut Pendaftaran");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("12345678910");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        jPasswordField2.setText("12345678910");
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setToolTipText("");

        jLabel2_closeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2_closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_closeButton.setText("X");
        jLabel2_closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_closeButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_ReUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jPasswordField2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1_ReUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userName = jTextField1_ReUsername.getText();
        password = String.valueOf(jPasswordField1.getPassword());
        String conPassword = String.valueOf(jPasswordField2.getPassword());

        varifyFields();

        if (varifyFields() == true && !checkUser(userName)) {
            Halaman_utama utama = new Halaman_utama();
            utama.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2_closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_closeButtonMouseClicked

        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jLabel2_closeButtonMouseClicked

    private void jLabel2_closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_closeButtonMouseEntered
        // TODO add your handling code here:

        Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);

        //border for closing button
        jLabel2_closeButton.setBorder(closeMin);
        jLabel2_closeButton.setForeground(Color.red);

    }//GEN-LAST:event_jLabel2_closeButtonMouseEntered

    private void jLabel2_closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_closeButtonMouseExited
        // TODO add your handling code here:
        Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);

        //border for closing button
        jLabel2_closeButton.setBorder(closeMin);
        jLabel2_closeButton.setForeground(Color.black);

    }//GEN-LAST:event_jLabel2_closeButtonMouseExited

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
          String LogInPassword = String.valueOf(jPasswordField1.getPassword());
        
        if ( LogInPassword.trim().toLowerCase().equals("12345678910"))
        {
            jPasswordField1.setText("");
            jPasswordField1.setForeground(Color.black);
                  
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        String LogInPassword = String.valueOf(jPasswordField1.getPassword());

        
        if (LogInPassword.trim().equals("") || 
            LogInPassword.trim().toLowerCase().equals("12345678910") )
            
        {
            
            jPasswordField1.setText("12345678910");
         
            
        }
        
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
        String LogInPassword = String.valueOf(jPasswordField2.getPassword());
        
        if ( LogInPassword.trim().toLowerCase().equals("12345678910"))
        {
            jPasswordField2.setText("");
            jPasswordField2.setForeground(Color.black);
                  
        }
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
        String LogInPassword = String.valueOf(jPasswordField2.getPassword());

        
        if (LogInPassword.trim().equals("") || 
            LogInPassword.trim().toLowerCase().equals("12345678910") )
            
        {
            
            jPasswordField2.setText("12345678910");
         
            
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jTextField1_ReUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_ReUsernameKeyTyped
        // TODO add your handling code here:
         if (jTextField1_ReUsername.getText().length() >= 20) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_jTextField1_ReUsernameKeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
        if (jPasswordField1.getText().length() >= 30) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        logInMenu login=new logInMenu();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public boolean varifyFields ()
    {
        
    String userName = jTextField1_ReUsername.getText();
    String password = String.valueOf(jPasswordField1.getPassword());
    String conPassword = String.valueOf(jPasswordField2.getPassword());
    
        if (userName.trim().equals("")|| password.trim().equals("") || conPassword.trim().equals("")) {

            JOptionPane.showMessageDialog(null, "Inputan kosong", "eror inputan", 2);
            return false;

        } else if (!password.equals(conPassword)) {
            JOptionPane.showMessageDialog(null, "password tidak sama", "error password", 2);
            return false;
        } else {
            return true;
        }
    
    }
     
    public boolean checkUser(String userName){
    
        PreparedStatement PreparedStatement;
        ResultSet ResultSet;
        boolean userExist = false;
        
        String query = "SELECT * FROM `Tabel_Pendaftaran` WHERE `usernameid` = ?";
        
        
           try {
              Connection conn = (Connection) DBConnection.connectDatabase();    
            PreparedStatement =conn.prepareStatement(query);
            PreparedStatement.setString(1, userName);
            ResultSet = PreparedStatement.executeQuery();
        
            if(ResultSet.next())
            {
                userExist = true;
                JOptionPane.showMessageDialog(null, "Akun telah ada", "Username gagal", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return userExist;
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new registration().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_closeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    public static javax.swing.JTextField jTextField1_ReUsername;
    // End of variables declaration//GEN-END:variables
}
